language: generic
sudo: required

services:
 - docker

before_install:
 - docker build -t rajivpuranik/docker-react -f Dockerfile.dev .
 
script:
 - docker run  -e CI=true rajivpuranik/docker-react  npm run test 
